spring.application.name=restaurant-system
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/restaurant_system}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
